/**
 * Somnia Reactivity SDK integration.
 * - Off-chain: WebSocket subscriptions (subscribe, wildcard subscribe).
 * - On-chain: createSoliditySubscription, getSubscriptionInfo, cancelSoliditySubscription.
 * - System events / cron (SDK ≥0.1.9): BlockTick subscription, Schedule (one-off cron) via
 *   createOnchainBlockTickSubscription, scheduleOnchainCronJob.
 * @see https://docs.somnia.network/developer/reactivity/tutorials/cron-subscriptions-via-sdk
 * @see https://docs.somnia.network/developer/reactivity/system-events
 */

// All reactivity code is generated by the @somnia-chain/reactivity package.
import { SDK } from "@somnia-chain/reactivity";
import { createPublicClient, http, webSocket } from "viem";
import type { Address, Hex } from "viem";
import { somniaTestnet } from "./wagmi";
import {
  JSON_RPC_PROVIDER,
  SOMNIA_WSS_RPC,
  GAME_CONTRACT_ADDRESS,
} from "./config";

/** Params for off-chain subscribe (ethCalls, onData, optional eventTopics, origin, emitter, etc.). */
export interface SubscriptionInitParams {
  ethCalls?: Array<{ to: Address; data: Hex }>;
  onData: (data: unknown) => void;
  onError?: (err: unknown) => void;
  eventTopics?: Hex[];
  origin?: Address;
  emitter?: Address;
  caller?: Address;
}

/** On-chain subscription config for createSoliditySubscription. */
export interface SoliditySubscriptionData {
  handlerContractAddress: Address;
  priorityFeePerGas: bigint;
  maxFeePerGas: bigint;
  gasLimit: bigint;
  isGuaranteed: boolean;
  isCoalesced: boolean;
  eventTopics?: Hex[];
  origin?: Address;
  caller?: Address;
  emitter?: Address;
  handlerFunctionSelector?: Hex;
}

/** Result of getSubscriptionInfo. */
export interface SoliditySubscriptionInfo {
  subscriptionData: SoliditySubscriptionData;
  owner: Address;
}

/** Subscription handle returned by off-chain subscribe (call .unsubscribe() to stop). */
export interface OffChainSubscription {
  unsubscribe: () => void;
}

/**
 * Create a reactivity SDK instance.
 * Use publicClient + walletClient for full features (including createSoliditySubscription).
 * For off-chain subscribe only, publicClient is enough; use a transport that supports
 * WebSocket (e.g. createReactivityPublicClientWebSocket()) for push notifications.
 * wallet: pass wagmi's useWalletClient().data or any viem-compatible WalletClient.
 */
export function createReactivitySDK(options: {
  public: ReturnType<typeof createPublicClient>;
  wallet?: unknown;
}): SDK {
  return new SDK(options as ConstructorParameters<typeof SDK>[0]);
}

/** Public client with HTTP transport (read-only / on-chain tx; use for createSoliditySubscription with wallet). */
export function createReactivityPublicClientHttp() {
  return createPublicClient({
    chain: somniaTestnet,
    transport: http(JSON_RPC_PROVIDER),
  });
}

/** Public client with WebSocket transport for off-chain push subscriptions. */
export function createReactivityPublicClientWebSocket() {
  return createPublicClient({
    chain: somniaTestnet,
    transport: webSocket(SOMNIA_WSS_RPC),
  });
}

/**
 * Start an off-chain (WebSocket) subscription.
 * Requires a public client with WebSocket transport for real-time push.
 * Returns an object with unsubscribe() to stop listening.
 */
export async function subscribeOffChain(
  publicClient: ReturnType<typeof createPublicClient>,
  initParams: SubscriptionInitParams
): Promise<OffChainSubscription | undefined> {
  const sdk = createReactivitySDK({ public: publicClient });
  const params = {
    ...initParams,
    ethCalls: initParams.ethCalls ?? [],
  };
  const sub = await sdk.subscribe(params as Parameters<SDK["subscribe"]>[0]);
  if (!sub || sub instanceof Error || typeof (sub as { unsubscribe?: () => void }).unsubscribe !== "function") {
    return undefined;
  }
  return {
    unsubscribe: () => (sub as { unsubscribe: () => void }).unsubscribe(),
  };
}

/**
 * Wildcard off-chain subscription: listen to all events (no eventTopics filter).
 * Omit or leave eventTopics empty to receive every matching event from the chain.
 */
export async function subscribeOffChainWildcard(
  publicClient: ReturnType<typeof createPublicClient>,
  initParams: Omit<SubscriptionInitParams, "eventTopics"> & {
    eventTopics?: never;
  }
): Promise<OffChainSubscription | undefined> {
  return subscribeOffChain(publicClient, { ...initParams, eventTopics: undefined });
}

/**
 * Create an on-chain (Solidity) subscription. Requires wallet client; owner must hold ≥32 STT.
 * Returns transaction hash on success, or an Error.
 */
export async function createSoliditySubscription(
  sdk: SDK,
  data: SoliditySubscriptionData
): Promise<`0x${string}` | Error> {
  return sdk.createSoliditySubscription(data);
}

/** Get on-chain subscription info by ID. */
export async function getSubscriptionInfo(
  sdk: SDK,
  subscriptionId: bigint
): Promise<SoliditySubscriptionInfo | Error> {
  return sdk.getSubscriptionInfo(subscriptionId);
}

/** Cancel an on-chain subscription. Only owner can cancel. Returns tx hash or Error. */
export async function cancelSoliditySubscription(
  sdk: SDK,
  subscriptionId: bigint
): Promise<`0x${string}` | Error> {
  return sdk.cancelSoliditySubscription(subscriptionId);
}

/** Params for BlockTick system event (every block, or at a specific block if blockNumber set). */
export interface BlockTickSubscriptionParams {
  handlerContractAddress: Address;
  blockNumber?: bigint;
  handlerFunctionSelector?: Hex;
  priorityFeePerGas: bigint;
  maxFeePerGas: bigint;
  gasLimit: bigint;
  isGuaranteed: boolean;
  isCoalesced: boolean;
}

/**
 * Create on-chain BlockTick subscription (system event at every block, or at blockNumber if set).
 * Requires wallet; owner must hold ≥32 STT. SDK ≥0.1.9.
 */
export async function createOnchainBlockTickSubscription(
  sdk: SDK,
  params: BlockTickSubscriptionParams
): Promise<`0x${string}` | Error> {
  if (typeof sdk.createOnchainBlockTickSubscription !== "function") {
    return new Error("@somnia-chain/reactivity@0.1.9+ required for createOnchainBlockTickSubscription");
  }
  return sdk.createOnchainBlockTickSubscription(params as Parameters<SDK["createOnchainBlockTickSubscription"]>[0]);
}

/** Params for Schedule system event (one-off cron at timestampMs; min ~12s in the future, in milliseconds). */
export interface ScheduleCronJobParams {
  timestampMs: number | bigint;
  handlerContractAddress: Address;
  handlerFunctionSelector?: Hex;
  priorityFeePerGas: bigint;
  maxFeePerGas: bigint;
  gasLimit: bigint;
  isGuaranteed: boolean;
  isCoalesced: boolean;
}

/**
 * Schedule a one-off on-chain cron job (Schedule system event). Subscription is deleted after triggering.
 * Timestamp must be in the future (e.g. at least 12 seconds). SDK ≥0.1.9.
 */
export async function scheduleOnchainCronJob(
  sdk: SDK,
  params: ScheduleCronJobParams
): Promise<`0x${string}` | Error> {
  if (typeof sdk.scheduleOnchainCronJob !== "function") {
    return new Error("@somnia-chain/reactivity@0.1.9+ required for scheduleOnchainCronJob");
  }
  return sdk.scheduleOnchainCronJob(params as Parameters<SDK["scheduleOnchainCronJob"]>[0]);
}

/** Default handler contract for ZKGameClient reactivity (this repo's game contract). */
export const DEFAULT_HANDLER_CONTRACT_ADDRESS = GAME_CONTRACT_ADDRESS as `0x${string}`;
